// <auto-generated />
using System;
using KotoNeko.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KotoNeko.Data.Migrations
{
    [DbContext(typeof(KotoNekoDbContext))]
    [Migration("20260616060122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KotoNeko.Core.Domain.Conjugation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedKana")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<int>("Polarity")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId", "Form", "Polarity")
                        .IsUnique();

                    b.ToTable("Conjugations");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.ReviewLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConjugationForm")
                        .HasColumnType("int");

                    b.Property<int?>("ConjugationPolarity")
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StageAtReview")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedAt");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("WasCorrect");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.SourceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceMaterials");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.SrsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BurnedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("Stage");

                    b.HasIndex("VocabularyId")
                        .IsUnique();

                    b.ToTable("SrsItems");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateMeanings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("AlternateReadings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("ContextSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAsleep")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Memo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("VerbClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsAsleep");

                    b.HasIndex("SourceMaterialId");

                    b.ToTable("Vocabulary");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.Conjugation", b =>
                {
                    b.HasOne("KotoNeko.Core.Domain.Vocabulary", "Vocabulary")
                        .WithMany("Conjugations")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.ReviewLog", b =>
                {
                    b.HasOne("KotoNeko.Core.Domain.Vocabulary", "Vocabulary")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.SrsItem", b =>
                {
                    b.HasOne("KotoNeko.Core.Domain.Vocabulary", "Vocabulary")
                        .WithOne("Srs")
                        .HasForeignKey("KotoNeko.Core.Domain.SrsItem", "VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.Vocabulary", b =>
                {
                    b.HasOne("KotoNeko.Core.Domain.SourceMaterial", "SourceMaterial")
                        .WithMany("Vocabulary")
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.SourceMaterial", b =>
                {
                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("KotoNeko.Core.Domain.Vocabulary", b =>
                {
                    b.Navigation("Conjugations");

                    b.Navigation("ReviewLogs");

                    b.Navigation("Srs");
                });
#pragma warning restore 612, 618
        }
    }
}
