namespace KotoNeko.Core.Domain;

/// <summary>
/// A single stored conjugation for a verb (one form + polarity), generated by the
/// conjugation engine and editable in the admin UI. Quizzed on during reviews.
/// </summary>
public class Conjugation
{
    public int Id { get; set; }

    public int VocabularyId { get; set; }
    public Vocabulary? Vocabulary { get; set; }

    public ConjugationForm Form { get; set; }

    public Polarity Polarity { get; set; }

    /// <summary>The expected conjugated form, in kana, e.g. はなさなかった.</summary>
    public string ExpectedKana { get; set; } = string.Empty;
}
